@startuml
title Diagrama de Clases - Aplicación Barbería

left to right direction
' === Paquete de Interfaz (UI / Presentación) ===
package "Interfaz" {

	class PantallaAdmin {
	+ MostrarEmpleados() : void
	+ RegistrarEmpleados() : void
	+ EliminarEmpleados() : void
	}

    class PantallaPrincipal {
        + mostrarMenu(): void
        + mostrarVentanas() : void
    }

    class GestionCitasUI {
        + mostrarCitas(): void
        + crearCita(): void
        + cancelarCita(): void
    }

    class GestionClientesUI {
        + registrarCliente(): void
        + mostrarClientes(): void
    }

    class GestionPagosUI {
        + procesarPago(): void
        + mostrarHistorialPagos(): void
    }

    class Login {
    + verificarRol() : void
    + iniciarSesion() : void
}
}

' === Paquete de Dominio / Lógica ===
package "Dominio" {

    abstract class Persona {
        - id: int
        - nombre: String
        - telefono: String
        - correo: String
        
    }

    class Cliente {
    - PuntosFidelidad : int
    }

    class Barbero {
        - especialidad: String
        - disponible: boolean
        + asignarCita(): void
        + actualizarDisponibilidad(): void
        + mostrarHorarios(): void
    }
    
    interface Usuario {
    
    + registrar(): void
    + actualizarDatos(): void
}

	abstract class UsuarioBase extends Persona {
	- user : String
	- contraseña : String
	- rol : String
	}
    
    class UsuarioRegular extends usuarioBase implements Usuario {
    }
    class Admin extends UsuarioBase implements Usuario{
    - nivelAcceso : int
    }


    class Cita {
        - idCita: int
        - fecha: Date
        - hora: String
        - estado: String
        + agendarCita(): void
        + cancelarCita(): void
        + actualizarEstado(): void
    }

    class Servicio {
        - idServicio: int
        - nombre: String
        - precio: double
        - duracion: int
        + agregarServicio(): void
        + editarServicio(): void
        + consultarPrecio(): double
    }

    class Pago {
        - idPago: int
        - monto: double
        - metodoPago: String
        - fechaPago: Date
        + registrarPago(): void
        + consultarPago(): void
    }

    ' Herencia
    Persona <|-- Cliente
    Persona <|-- Barbero
}

' === Paquete de Persistencia / Datos ===
package "Persistencia" {
    class BaseDatos {
        + conectar(): void
        + guardarDatos(objeto): void
        + consultarDatos(tabla: String): void
    }
}

' === Relaciones internas ===
Cliente  --  Cita 
Barbero  --  Cita 
Cita  --  Pago 
Cita  --  Servicio  

' === Relaciones entre paquetes ===
GestionClientesUI --> Cliente 
GestionCitasUI --> Cita 
GestionPagosUI --> Pago 
Dominio --> Persistencia 
Login --> Usuario
@enduml
